"""Add football match fields to events

Revision ID: 042c678f0d72
Revises: 004_add_user_contact_fields
Create Date: 2026-01-07 10:01:04.702250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '042c678f0d72'
down_revision: Union[str, None] = '004_add_user_contact_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_renewals_activation_token'), table_name='pending_renewals')
    op.drop_index(op.f('ix_pending_renewals_email'), table_name='pending_renewals')
    op.drop_index(op.f('ix_pending_renewals_id'), table_name='pending_renewals')
    op.drop_table('pending_renewals')
    op.drop_index(op.f('ix_signup_activities_email'), table_name='signup_activities')
    op.drop_index(op.f('ix_signup_activities_id'), table_name='signup_activities')
    op.drop_index(op.f('ix_signup_activities_included_in_report'), table_name='signup_activities')
    op.drop_index(op.f('ix_signup_activities_signup_date'), table_name='signup_activities')
    op.drop_index(op.f('ix_signup_activities_user_id'), table_name='signup_activities')
    op.drop_table('signup_activities')
    op.add_column('events', sa.Column('is_football_match', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('home_team', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('away_team', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('football_competition', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('events_slug_key'), 'events', type_='unique')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_is_football_match'), 'events', ['is_football_match'], unique=False)
    op.drop_column('pending_registrations', 'spouse_card_name')
    op.drop_column('pending_registrations', 'is_renewal')
    op.drop_column('pending_registrations', 'membership_id')
    op.drop_column('pending_registrations', 'needs_replacement_card')
    op.drop_index(op.f('ix_users_membership_id'), table_name='users')
    op.drop_column('users', 'spouse_card_name')
    op.drop_column('users', 'membership_id')
    op.drop_column('users', 'needs_replacement_card')
    op.drop_column('users', 'membership_id_reminder_sent')
    op.drop_column('users', 'is_renewal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_renewal', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('membership_id_reminder_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('needs_replacement_card', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('membership_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_card_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_membership_id'), 'users', ['membership_id'], unique=False)
    op.add_column('pending_registrations', sa.Column('needs_replacement_card', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('pending_registrations', sa.Column('membership_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('pending_registrations', sa.Column('is_renewal', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('pending_registrations', sa.Column('spouse_card_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_is_football_match'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=False)
    op.create_unique_constraint(op.f('events_slug_key'), 'events', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('events', 'football_competition')
    op.drop_column('events', 'away_team')
    op.drop_column('events', 'home_team')
    op.drop_column('events', 'is_football_match')
    op.create_table('signup_activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('has_spouse_card', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('amount_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('stripe_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('membership_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('signup_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('newsletter_subscribed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('included_in_report', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('report_sent_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_renewal', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('membership_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('needs_replacement_card', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('spouse_card_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('signup_activities_pkey'))
    )
    op.create_index(op.f('ix_signup_activities_user_id'), 'signup_activities', ['user_id'], unique=False)
    op.create_index(op.f('ix_signup_activities_signup_date'), 'signup_activities', ['signup_date'], unique=False)
    op.create_index(op.f('ix_signup_activities_included_in_report'), 'signup_activities', ['included_in_report'], unique=False)
    op.create_index(op.f('ix_signup_activities_id'), 'signup_activities', ['id'], unique=False)
    op.create_index(op.f('ix_signup_activities_email'), 'signup_activities', ['email'], unique=False)
    op.create_table('pending_renewals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('activation_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('membership_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('newsletter', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('wants_replacement_card', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_renewals_pkey'))
    )
    op.create_index(op.f('ix_pending_renewals_id'), 'pending_renewals', ['id'], unique=False)
    op.create_index(op.f('ix_pending_renewals_email'), 'pending_renewals', ['email'], unique=False)
    op.create_index(op.f('ix_pending_renewals_activation_token'), 'pending_renewals', ['activation_token'], unique=True)
    # ### end Alembic commands ###
